config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :games, only: [:index, :create, :show] do
    resources :parties, only: %i[new create index show] do
      resources :solutions, only: %i[new create index show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :user
  has_many :parties
end

app/models/party.rb
# frozen_string_literal: true

class Party < ApplicationRecord
  belongs_to :game
  has_many :solutions

  def ten_letters_list
    vowels = %w[a e i o u]
    consonants = %w[b c d f g h j k l m n p q r s t v w x y z]
    ten_letters = []
    5.times do
      ten_letters << vowels.sample
    end
    5.times do
      ten_letters << consonants.sample
    end
    ten_letters.shuffle.join.to_s
  end

  def self.verif_word(ten_letters_list, word)
    check_word = Hash.new(0)
    ten_letters_list.each_char { |letter| check_word[letter.downcase] += 1 }
    word.each_char { |letter| check_word[letter.downcase] -= 1 }
    check_word.values.all? { |value| value >= 0 }
  end

  def score
    return 0 if word.nil? || word.blank?
    word.length
  end
end

app/models/solution.rb
# frozen_string_literal: true

class Solution < ApplicationRecord
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController
 
  def home
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def create
    @game = Game.new(user: current_user)
    if @game.save
      redirect_to game_path(@game)
    else
      render :index
    end
  end

  def show
    @game = Game.find(params[:id])
    @parties = @game.parties
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def new
    @game = Game.find(params[:game_id])
    if @game.parties.count < 5
      @party = @game.parties.new
    else
      flash[:alert] = "vous ne pouvez pas créer plus de 5 parties dans ce jeu"
      redirect_to game_path(@game)
    end
  end

  def create
    @game = Game.find(params[:game_id])
    if @game.parties.count < 5
      @party = @game.parties.new(party_params)
      @party.game = @game
      @party.ten_letters_list = Party.new.ten_letters_list
      if Party.verif_word(@party.ten_letters_list, @party.word)
        if @party.save
          redirect_to game_party_path(@game, @party)
        else
          render :new
        end
      else
        flash[:alert] = "Le mot '#{@party.word}' n'est pas valide."
      render :new
      end
    else
      flash[:alert] = "vous ne pouvez pas créer plus de 5 parties dans ce jeu"
      redirect_to game_path(@game)
    end
  end

  def show
    @party = Party.find(params[:id])
    @game = @party.game
  end

  private

  def party_params
    params.require(:party).permit(:word)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/games/index.html.erb
<div class="container">
  <div class="row">
  <%# bloc pour le titre de la page %>
    <div class="d-flex justify-content-center">
      <% %w[R E G L E S].each do |letter| %>
        <div class="letter-cards">
          <%= letter %>
        </div>
      <% end %>
    </div>
    <%# bloc pour la card des règles du jeu %>
    <div class="rules-card">
      <p>Vous devrez composer un mot à partir d'une liste de 10 lettres aléatoires.</p>
      <ul>
       <li>Bien évidemment, aucuns mots inventés ne sera validé</li>
        <li>Seul un mot présent dans le dictionnaire sera valable.</li>
        <li>Si le mot est validé, alors vous gagnerez 1 point par lettre qui compose le mot.</li>
        <li>Chaque partie est composé de 5 manches. Tenez de battre votre record!</li>
      </ul>
    <%# <%= link_to "Commencer une nouvelle partie", games_path, method: :post, class: "btn btn-primary rounded-pill" %>
      <%= form_with url: games_path, method: :post, local: true do %>
        <%= submit_tag "Commencer un nouveau jeu", class: "custom-btn" %>
      <% end %>
      </div>

  </div>
</div>


<% @games.each do |game| %>
  <div class="container game-recap-card">
    <div class="row">
      <div class="col-12">
      <%# affichage de l'ID du jeu %>
        <h2>Jeu n° <%= game.id %> </h2>
      <%# affichage du score total d'une game %>
        <p>Score total: <%= game.parties.sum { |party| party.score } %></p>
      <%# affichage du mot et du score de chaque party correspondante à la game %>
        <% game.parties.each do |party| %>
          <div class="party-tab">
            <p>partie n° <%= party.id %> </p>
            <p>Votre mot: <%= party.word %> </p>
            <p>Votre score: <%= party.score %> </p>
          </div>
        <% end %>
      </div>
    <div class="blocparty">
    <%= link_to "Jeu en cours", game_path(game), class:"current-game-access-btn" %>
    </div>
  </div>
</div>
<% end %>

app/views/games/show.html.erb
<%# on fait un simple form avec un affichage ndes 10 lettres qu'on définit et génère dans le modele %>
<%# on a le formulaire ou le joueur peut rentrer son mot le plus long %>
<%# avec une validation on check si le mot est correct %>
<%# check dico %>
<%# si c'est ok, on est redirigé sur le show %>
<%# on affiche les 10 lettres générées précédemment avec le mot et une formule de calcul de points %>
<%# on affiche un bouton pour recommencer %>

<div class="container">
  <div class="row">
  <%# bloc pour le titre de la page %>
    <div class="d-flex justify-content-center">
      <% %w[P A R T I E ° ].each do |letter| %>
        <div class="letter-cards">
          <%= letter %>
        </div>
      <% end %>
      <div class="letter-cards party-number-card">
        <%= @game.id %>
      </div>
    </div>


  <%# bloc pour la card des règles du jeu %>
    <div class="rules-card">
      <p>Vous devrez composer un mot à partir d'une liste de 10 lettres aléatoires.</p>
      <ul>
       <li>Bien évidemment, aucuns mots inventés ne sera validé</li>
        <li>Seul un mot présent dans le dictionnaire sera valable.</li>
        <li>Si le mot est validé, alors vous gagnerez 1 point par lettre qui compose le mot.</li>
        <li>Chaque partie est composé de 5 manches. Tenez de battre votre record!</li>
      </ul>
      <h1> Pour démarrer une nouvelle partie, c'est juste en dessous! </h1>
      <div>
        <%= link_to "Nouvelle partie", new_game_party_path(@game), class: "custom-btn" %>
      </div>
    </div>
  </div>
</div>


<% @game.parties.each_with_index do |party, index| %>
  <div class="container party-recap-card">
    <div class="row">
      <div class="col-12">
        <h2>Partie n° <%= index + 1 %> en cours </h2>
        <p>Score: <%= party.word.length %> </p>
        <p>Votre mot: <%= party.word %> </p>
        <%= link_to "Détails", game_party_path(@game), class:"custom-btn" %>
      </div>
    </div>
  </div>
<% end %>
  <%= link_to "revenir au récapitulatif des jeux", games_path(@game), class:"custom-btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render "shared/navbar" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>

    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
    <% %w[L O N G E S T - W O R D].each do |letter| %>
      <div class="letter-cards">
        <%= letter %>
      </div>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "JOUER", games_path, class:"home-enter-btn" %>
  </div>
</div>

app/views/parties/new.html.erb
<%# on met un formulaire simple form en place %>
<div class="d-flex justify-content-center">
  <% @party.ten_letters_list.chars.each do |letter| %>
    <div class="letter-cards">
      <%= letter %>
    </div>
  <% end %>
</div>

<%= simple_form_for [@game, @party] do |f| %>
  <%= f.input :word, label: "Votre mot le plus long", required: true %>
  <%= f.submit "Valider", class: "custom-btn" %>
<% end %>
<%# on affiche les 10 lettres générées %>
<%# on a un champ pour rentrer le mot %>
<%# on a un bouton pour valider %>
<%# on a un bouton pour recommencer %>
<%# on affiche le mot et le score %>
<%# on affiche un bouton pour recommencer %>
<%# on affiche un bouton pour retourner à l'index %>
<%# on affiche un bouton pour retourner à la partie en cours %>
<%= link_to "Retour au jeu en cours", game_path(@game), class: "custom-btn" %>

app/views/parties/show.html.erb
<h2>Votre score est de <%= @party.word.length %></h2>
<h2>votre mot est <%= @party.word %></h2>
<h2></h2>
<%= link_to "retour en arrière", game_path(@game), class:"btn btn-primary rounded-pill" %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>